/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

//declare array to store fibonacci values and variables for lower/upper fibonacci addends and sum of results
resultContainer= [];
var fib = 1;
var fib_1 = 1;
var sum = 0;
  	
//a while loop to run a fibonacci sequence, and push even results to an array for later processing		
while (fib < 4000000) {
		var next = fib + fib_1;
			if (next % 2 == 0){
			resultContainer.push(next);
	}
		fib = fib_1;
		fib_1 = next; 
}

//adding each number in the array to produce the answer to the problem
for (z=0, j= resultContainer.length; z<j; z++) {
sum += resultContainer[z];
}

console.log(sum);
